repos:
  - repo: https://github.com/psf/black
    rev: 24.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0
    hooks:
      - id: isort
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.300
    hooks:
      - id: ruff
